version: '3.0'

services:
 mongodb:
  image: mongo:latest
  ports:
   - "27017:27017"
  restart: always

 nest: 
  build: .
  ports:
  - "3000:3000"
  links:
  - mongodb
  restart: always
  environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb:27017/phonebook